      Rename precision_recall_curve.png bug fix  (#1431)          * fix error in train.py line 400, changed precision-recall_curve.png to precision_recall_curve.png and fix error in test.py of {wandb.init() before wandb.log()} by importing wand and initializing it before wand.log()          * Update test.py          Co-authored-by: Glenn Jocher <glenn.jocher@ultralytics.com> 
             plot_results(save_dir=save_dir)  # save as results.png              if wandb:                  wandb.log({"Results": [wandb.Image(str(save_dir / x), caption=x) for x in                                        ['results.png', 'precision-recall_curve.png']]})                                        ['results.png', 'precision_recall_curve.png']]})          logger.info('%g epochs completed in %.3f hours.\n' % (epoch - start_epoch + 1, (time.time() - t0) / 3600))      else:          dist.destroy_process_group() 
