      pretrained model loading bug fix (#450)          Signed-off-by: Glenn Jocher <glenn.jocher@ultralytics.com> 
           # load model          try:             ckpt['model'] = {k: v for k, v in ckpt['model'].float().state_dict().items() if k in model.state_dict()}             ckpt['model'] = {k: v for k, v in ckpt['model'].float().state_dict().items()                              if k in model.state_dict() and model.state_dict()[k].shape == v.shape}              model.load_state_dict(ckpt['model'], strict=False)          except KeyError as e:              s = "%s is not compatible with %s. This may be due to model differences or %s may be out of date. " \ 
